simplified_hockey_stats_schema = {
    "goalie_stats_playoffs": {
        "playerId": "Identifier for the player.",
        "name": "Name of the player.",
        "team": "3 Letter abbreviation of the players team",
        "season": "Season in which the data was recorded.",
        "position": "Position of the player as a letter (G, D, L, R, C).",
        "games_played": "Number of games played by the goalie.",
        "icetime": "Total ice time of the goalie in minutes.",
        "xGoals": "Expected goals against.",
        "xRebounds": "Expected rebounds against.",
        "xFreeze": "Expected freezes against.",
        "xOnGoal": "Expected shots on goal against.",
        "xPlayStopped": "Expected play stoppages against.",
        "xPlayContinuedInZone": "Expected continued play in zone against.",
        "xPlayContinuedOutsideZone": "Expected continued play outside zone against.",
        "flurryAdjustedxGoals": "Flurry adjusted expected goals against.",
        "lowDangerxGoals": "Expected low danger goals against.",
        "mediumDangerxGoals": "Expected medium danger goals against.",
        "highDangerxGoals": "Expected high danger goals against.",
        "goals": "Total goals against.",
        "rebounds": "Total rebounds against.",
        "freeze": "Total freezes against.",
        "ongoal": "Total shots on goal against.",
        "playStopped": "Total play stoppages against.",
        "playContinuedInZone": "Total continued play in zone against.",
        "playContinuedOutsideZone": "Total continued play outside zone against.",
        "lowDangerGoals": "Total low danger goals against.",
        "mediumDangerGoals": "Total medium danger goals against.",
        "highDangerGoals": "Total high danger goals against.",
        "unblocked_shot_attempts": "Total unblocked shot attempts against.",
        "blocked_shot_attempts": "Total blocked shot attempts against.",
        "lowDangerShots": "Total low danger shots against.",
        "mediumDangerShots": "Total medium danger shots against.",
        "highDangerShots": "Total high danger shots against.",
        "penalityMinutes": "Total penalty minutes incurred by the goalie.",
        "penalties": "Total number of penalties incurred by the goalie."
    },
    "goalie_stats_regular_season": {
        "playerId": "Identifier for the player.",
        "name": "Name of the player.",
        "team": "3 Letter abbreviation of the players team",
        "season": "Season in which the data was recorded.",
        "position": "Position of the player as a letter (G, D, L, R, C).",
        "games_played": "Number of games played by the goalie.",
        "icetime": "Total ice time of the goalie in minutes.",
        "xGoals": "Expected goals against.",
        "xRebounds": "Expected rebounds against.",
        "xFreeze": "Expected freezes against.",
        "xOnGoal": "Expected shots on goal against.",
        "xPlayStopped": "Expected play stoppages against.",
        "xPlayContinuedInZone": "Expected continued play in zone against.",
        "xPlayContinuedOutsideZone": "Expected continued play outside zone against.",
        "flurryAdjustedxGoals": "Flurry adjusted expected goals against.",
        "lowDangerxGoals": "Expected low danger goals against.",
        "mediumDangerxGoals": "Expected medium danger goals against.",
        "highDangerxGoals": "Expected high danger goals against.",
        "goals": "Total goals against.",
        "rebounds": "Total rebounds against.",
        "freeze": "Total freezes against.",
        "ongoal": "Total shots on goal against.",
        "playStopped": "Total play stoppages against.",
        "playContinuedInZone": "Total continued play in zone against.",
        "playContinuedOutsideZone": "Total continued play outside zone against.",
        "lowDangerGoals": "Total low danger goals against.",
        "mediumDangerGoals": "Total medium danger goals against.",
        "highDangerGoals": "Total high danger goals against.",
        "unblocked_shot_attempts": "Total unblocked shot attempts against.",
        "blocked_shot_attempts": "Total blocked shot attempts against.",
        "lowDangerShots": "Total low danger shots against.",
        "mediumDangerShots": "Total medium danger shots against.",
        "highDangerShots": "Total high danger shots against.",
        "penalityMinutes": "Total penalty minutes incurred by the goalie.",
        "penalties": "Total number of penalties incurred by the goalie."
    },
    "lines_and_pairings": {
        "lineId": "Identifier for the line or pairing.",
        "name": "Name of the line or pairing.",
        "team": "3 Letter abbreviation of the players team",
        "season": "Season in which the data was recorded.",
        "position": "Position of the player as a letter (G, D, L, R, C).",
        "games_played": "Number of games played by the line or pairing.",
        "icetime": "Total ice time of the line or pairing in minutes.",
        "iceTimeRank": "Rank of ice time among all lines or pairings.",
        "xGoalsPercentage": "Expected goals percentage.",
        "corsiPercentage": "Corsi percentage, a measure of shot attempt differential.",
        "fenwickPercentage": "Fenwick percentage, a measure of unblocked shot attempt differential.",
        "xOnGoalFor": "Expected shots on goal for.",
        "xGoalsFor": "Expected goals for.",
        "xReboundsFor": "Expected rebounds for.",
        "xFreezeFor": "Expected freezes for.",
        "xPlayStoppedFor": "Expected play stoppages for.",
        "xPlayContinuedInZoneFor": "Expected continued play in zone for.",
        "xPlayContinuedOutsideZoneFor": "Expected continued play outside zone for.",
        "flurryAdjustedxGoalsFor": "Flurry adjusted expected goals for.",
        "scoreVenueAdjustedxGoalsFor": "Score and venue adjusted expected goals for.",
        "flurryScoreVenueAdjustedxGoalsFor": "Flurry, score, and venue adjusted expected goals for.",
        "lowDangerxGoalsFor": "Expected low danger goals for.",
        "mediumDangerxGoalsFor": "Expected medium danger goals for.",
        "highDangerxGoalsFor": "Expected high danger goals for.",
        "reboundxGoalsFor": "Expected goals from rebounds for.",
        "xGoalsFromxReboundsOfShotsFor": "Expected goals from expected rebounds of shots for.",
        "xGoalsFromActualReboundsOfShotsFor": "Expected goals from actual rebounds of shots for.",
        "xOnGoalAgainst": "Expected shots on goal against.",
        "xGoalsAgainst": "Expected goals against.",
        "xReboundsAgainst": "Expected rebounds against.",
        "xFreezeAgainst": "Expected freezes against.",
        "xPlayStoppedAgainst": "Expected play stoppages against.",
        "xPlayContinuedInZoneAgainst": "Expected continued play in zone against.",
        "xPlayContinuedOutsideZoneAgainst": "Expected continued play outside zone against.",
        "flurryAdjustedxGoalsAgainst": "Flurry adjusted expected goals against.",
        "scoreVenueAdjustedxGoalsAgainst": "Score and venue adjusted expected goals against.",
        "flurryScoreVenueAdjustedxGoalsAgainst": "Flurry, score, and venue adjusted expected goals against.",
        "lowDangerxGoalsAgainst": "Expected low danger goals against.",
        "mediumDangerxGoalsAgainst": "Expected medium danger goals against.",
        "highDangerxGoalsAgainst": "Expected high danger goals against.",
        "reboundxGoalsAgainst": "Expected goals from rebounds against.",
        "xGoalsFromxReboundsOfShotsAgainst": "Expected goals from expected rebounds of shots against.",
        "xGoalsFromActualReboundsOfShotsAgainst": "Expected goals from actual rebounds of shots against.",
        "goalsFor": "Total goals for.",
        "reboundsFor": "Total rebounds for.",
        "reboundGoalsFor": "Total rebound goals for.",
        "freezeFor": "Total freezes for.",
        "playStoppedFor": "Total play stoppages for.",
        "playContinuedInZoneFor": "Total continued play in zone for.",
        "playContinuedOutsideZoneFor": "Total continued play outside zone for.",
        "shotsOnGoalFor": "Total shots on goal for.",
        "missedShotsFor": "Total missed shots for.",
        "blockedShotAttemptsFor": "Total blocked shot attempts for.",
        "shotAttemptsFor": "Total shot attempts for.",
        "savedShotsOnGoalFor": "Total saved shots on goal for.",
        "savedUnblockedShotAttemptsFor": "Total saved unblocked shot attempts for.",
        "penaltiesFor": "Total penalties for.",
        "penalityMinutesFor": "Total penalty minutes for.",
        "faceOffsWonFor": "Total faceoffs won for.",
        "hitsFor": "Total hits for.",
        "takeawaysFor": "Total takeaways for.",
        "giveawaysFor": "Total giveaways for.",
        "lowDangerShotsFor": "Total low danger shots for.",
        "mediumDangerShotsFor": "Total medium danger shots for.",
        "highDangerShotsFor": "Total high danger shots for.",
        "lowDangerGoalsFor": "Total low danger goals for.",
        "mediumDangerGoalsFor": "Total medium danger goals for.",
        "highDangerGoalsFor": "Total high danger goals for.",
        "scoreAdjustedShotsAttemptsFor": "Score adjusted shot attempts for.",
        "unblockedShotAttemptsFor": "Total unblocked shot attempts for.",
        "scoreAdjustedUnblockedShotAttemptsFor": "Score adjusted unblocked shot attempts for.",
        "dZoneGiveawaysFor": "Total defensive zone giveaways for.",
        "totalShotCreditFor": "Total shot credit for.",
        "scoreAdjustedTotalShotCreditFor": "Score adjusted total shot credit for.",
        "scoreFlurryAdjustedTotalShotCreditFor": "Score and flurry adjusted total shot credit for.",
        "goalsAgainst": "Total goals against.",
        "reboundsAgainst": "Total rebounds against.",
        "reboundGoalsAgainst": "Total rebound goals against.",
        "freezeAgainst": "Total freezes against.",
        "playStoppedAgainst": "Total play stoppages against.",
        "playContinuedInZoneAgainst": "Total continued play in zone against.",
        "playContinuedOutsideZoneAgainst": "Total continued play outside zone against.",
        "shotsOnGoalAgainst": "Total shots on goal against.",
        "missedShotsAgainst": "Total missed shots against.",
        "blockedShotAttemptsAgainst": "Total blocked shot attempts against.",
        "shotAttemptsAgainst": "Total shot attempts against.",
        "savedShotsOnGoalAgainst": "Total saved shots on goal against.",
        "savedUnblockedShotAttemptsAgainst": "Total saved unblocked shot attempts against.",
        "penaltiesAgainst": "Total penalties against.",
        "penalityMinutesAgainst": "Total penalty minutes against.",
        "faceOffsWonAgainst": "Total faceoffs won against.",
        "hitsAgainst": "Total hits against.",
        "takeawaysAgainst": "Total takeaways against.",
        "giveawaysAgainst": "Total giveaways against.",
        "lowDangerShotsAgainst": "Total low danger shots against.",
        "mediumDangerShotsAgainst": "Total medium danger shots against.",
        "highDangerShotsAgainst": "Total high danger shots against.",
        "lowDangerGoalsAgainst": "Total low danger goals against.",
        "mediumDangerGoalsAgainst": "Total medium danger goals against.",
        "highDangerGoalsAgainst": "Total high danger goals against.",
        "scoreAdjustedShotsAttemptsAgainst": "Score adjusted shot attempts against.",
        "unblockedShotAttemptsAgainst": "Total unblocked shot attempts against.",
        "scoreAdjustedUnblockedShotAttemptsAgainst": "Score adjusted unblocked shot attempts against.",
        "dZoneGiveawaysAgainst": "Total defensive zone giveaways against.",
        "totalShotCreditAgainst": "Total shot credit against.",
        "scoreAdjustedTotalShotCreditAgainst": "Score adjusted total shot credit against.",
        "scoreFlurryAdjustedTotalShotCreditAgainst": "Score and flurry adjusted total shot credit against."
    },
    "lines_and_pairings_playoffs": {
        "lineId": "Identifier for the line or pairing.",
        "name": "Name of the line or pairing.",
        "team": "3 Letter abbreviation of the players team",
        "season": "Season in which the data was recorded.",
        "position": "Position of the player as a letter (G, D, L, R, C).",
        "games_played": "Number of games played by the line or pairing.",
        "icetime": "Total ice time of the line or pairing in minutes.",
        "iceTimeRank": "Rank of ice time among all lines or pairings.",
        "xGoalsPercentage": "Expected goals percentage.",
        "corsiPercentage": "Corsi percentage, a measure of shot attempt differential.",
        "fenwickPercentage": "Fenwick percentage, a measure of unblocked shot attempt differential.",
        "xOnGoalFor": "Expected shots on goal for.",
        "xGoalsFor": "Expected goals for.",
        "xReboundsFor": "Expected rebounds for.",
        "xFreezeFor": "Expected freezes for.",
        "xPlayStoppedFor": "Expected play stoppages for.",
        "xPlayContinuedInZoneFor": "Expected continued play in zone for.",
        "xPlayContinuedOutsideZoneFor": "Expected continued play outside zone for.",
        "flurryAdjustedxGoalsFor": "Flurry adjusted expected goals for.",
        "scoreVenueAdjustedxGoalsFor": "Score and venue adjusted expected goals for.",
        "flurryScoreVenueAdjustedxGoalsFor": "Flurry, score, and venue adjusted expected goals for.",
        "lowDangerxGoalsFor": "Expected low danger goals for.",
        "mediumDangerxGoalsFor": "Expected medium danger goals for.",
        "highDangerxGoalsFor": "Expected high danger goals for.",
        "reboundxGoalsFor": "Expected goals from rebounds for.",
        "xGoalsFromxReboundsOfShotsFor": "Expected goals from expected rebounds of shots for.",
        "xGoalsFromActualReboundsOfShotsFor": "Expected goals from actual rebounds of shots for.",
        "xOnGoalAgainst": "Expected shots on goal against.",
        "xGoalsAgainst": "Expected goals against.",
        "xReboundsAgainst": "Expected rebounds against.",
        "xFreezeAgainst": "Expected freezes against.",
        "xPlayStoppedAgainst": "Expected play stoppages against.",
        "xPlayContinuedInZoneAgainst": "Expected continued play in zone against.",
        "xPlayContinuedOutsideZoneAgainst": "Expected continued play outside zone against.",
        "flurryAdjustedxGoalsAgainst": "Flurry adjusted expected goals against.",
        "scoreVenueAdjustedxGoalsAgainst": "Score and venue adjusted expected goals against.",
        "flurryScoreVenueAdjustedxGoalsAgainst": "Flurry, score, and venue adjusted expected goals against.",
        "lowDangerxGoalsAgainst": "Expected low danger goals against.",
        "mediumDangerxGoalsAgainst": "Expected medium danger goals against.",
        "highDangerxGoalsAgainst": "Expected high danger goals against.",
        "reboundxGoalsAgainst": "Expected goals from rebounds against.",
        "xGoalsFromxReboundsOfShotsAgainst": "Expected goals from expected rebounds of shots against.",
        "xGoalsFromActualReboundsOfShotsAgainst": "Expected goals from actual rebounds of shots against.",
        "goalsFor": "Total goals for.",
        "reboundsFor": "Total rebounds for.",
        "reboundGoalsFor": "Total rebound goals for.",
        "freezeFor": "Total freezes for.",
        "playStoppedFor": "Total play stoppages for.",
        "playContinuedInZoneFor": "Total continued play in zone for.",
        "playContinuedOutsideZoneFor": "Total continued play outside zone for.",
        "shotsOnGoalFor": "Total shots on goal for.",
        "missedShotsFor": "Total missed shots for.",
        "blockedShotAttemptsFor": "Total blocked shot attempts for.",
        "shotAttemptsFor": "Total shot attempts for.",
        "savedShotsOnGoalFor": "Total saved shots on goal for.",
        "savedUnblockedShotAttemptsFor": "Total saved unblocked shot attempts for.",
        "penaltiesFor": "Total penalties for.",
        "penalityMinutesFor": "Total penalty minutes for.",
        "faceOffsWonFor": "Total faceoffs won for.",
        "hitsFor": "Total hits for.",
        "takeawaysFor": "Total takeaways for.",
        "giveawaysFor": "Total giveaways for.",
        "lowDangerShotsFor": "Total low danger shots for.",
        "mediumDangerShotsFor": "Total medium danger shots for.",
        "highDangerShotsFor": "Total high danger shots for.",
        "lowDangerGoalsFor": "Total low danger goals for.",
        "mediumDangerGoalsFor": "Total medium danger goals for.",
        "highDangerGoalsFor": "Total high danger goals for.",
        "scoreAdjustedShotsAttemptsFor": "Score adjusted shot attempts for.",
        "unblockedShotAttemptsFor": "Total unblocked shot attempts for.",
        "scoreAdjustedUnblockedShotAttemptsFor": "Score adjusted unblocked shot attempts for.",
        "dZoneGiveawaysFor": "Total defensive zone giveaways for.",
        "totalShotCreditFor": "Total shot credit for.",
        "scoreAdjustedTotalShotCreditFor": "Score adjusted total shot credit for.",
        "scoreFlurryAdjustedTotalShotCreditFor": "Score and flurry adjusted total shot credit for.",
        "goalsAgainst": "Total goals against.",
        "reboundsAgainst": "Total rebounds against.",
        "reboundGoalsAgainst": "Total rebound goals against.",
        "freezeAgainst": "Total freezes against.",
        "playStoppedAgainst": "Total play stoppages against.",
        "playContinuedInZoneAgainst": "Total continued play in zone against.",
        "playContinuedOutsideZoneAgainst": "Total continued play outside zone against.",
        "shotsOnGoalAgainst": "Total shots on goal against.",
        "missedShotsAgainst": "Total missed shots against.",
        "blockedShotAttemptsAgainst": "Total blocked shot attempts against.",
        "shotAttemptsAgainst": "Total shot attempts against.",
        "savedShotsOnGoalAgainst": "Total saved shots on goal against.",
        "savedUnblockedShotAttemptsAgainst": "Total saved unblocked shot attempts against.",
        "penaltiesAgainst": "Total penalties against.",
        "penalityMinutesAgainst": "Total penalty minutes against.",
        "faceOffsWonAgainst": "Total faceoffs won against.",
        "hitsAgainst": "Total hits against.",
        "takeawaysAgainst": "Total takeaways against.",
        "giveawaysAgainst": "Total giveaways against.",
        "lowDangerShotsAgainst": "Total low danger shots against.",
        "mediumDangerShotsAgainst": "Total medium danger shots against.",
        "highDangerShotsAgainst": "Total high danger shots against.",
        "lowDangerGoalsAgainst": "Total low danger goals against.",
        "mediumDangerGoalsAgainst": "Total medium danger goals against.",
        "highDangerGoalsAgainst": "Total high danger goals against.",
        "scoreAdjustedShotsAttemptsAgainst": "Score adjusted shot attempts against.",
        "unblockedShotAttemptsAgainst": "Total unblocked shot attempts against.",
        "scoreAdjustedUnblockedShotAttemptsAgainst": "Score adjusted unblocked shot attempts against.",
        "dZoneGiveawaysAgainst": "Total defensive zone giveaways against.",
        "totalShotCreditAgainst": "Total shot credit against.",
        "scoreAdjustedTotalShotCreditAgainst": "Score adjusted total shot credit against.",
        "scoreFlurryAdjustedTotalShotCreditAgainst": "Score and flurry adjusted total shot credit against."
    },
    "player_stats_regular_season": {
        "player_id": "Identifier for the player.",
        "name": "Name of the player.",
        "team": "3 Letter abbreviation of the players team",
        "season": "Season in which the data was recorded.",
        "position": "Position of the player as a letter (G, D, L, R, C).",
        "search_vector": "Search vector for text search capabilities.",
        "games_played": "Number of games played by the player.",
        "icetime": "Total ice time of the player in minutes.",
        "shifts": "Total number of shifts taken by the player.",
        "icetimerank": "Rank of ice time among all players.",
        "timeonbench": "Total time spent on the bench by the player in minutes.",
        "gamescore": "Overall game score rating for the player.",
        "onice_xgoalspercentage": "On-ice expected goals percentage.",
        "office_xgoalspercentage": "Off-ice expected goals percentage.",
        "onice_corsipercentage": "On-ice Corsi percentage, a measure of shot attempt differential.",
        "office_corsipercentage": "Off-ice Corsi percentage, a measure of shot attempt differential.",
        "onice_fenwickpercentage": "On-ice Fenwick percentage, a measure of unblocked shot attempt differential.",
        "office_fenwickpercentage": "Off-ice Fenwick percentage, a measure of unblocked shot attempt differential.",
        "i_f_xongoal": "Expected shots on goal for the player.",
        "i_f_xgoals": "Expected goals for the player.",
        "i_f_xrebounds": "Expected rebounds for the player.",
        "i_f_xfreeze": "Expected freezes for the player.",
        "i_f_xplaystopped": "Expected play stoppages for the player.",
        "i_f_xplaycontinuedinzone": "Expected continued play in zone for the player.",
        "i_f_xplaycontinuedoutsidezone": "Expected continued play outside zone for the player.",
        "i_f_flurryadjustedxgoals": "Flurry adjusted expected goals for the player.",
        "i_f_scorevenueadjustedxgoals": "Score and venue adjusted expected goals for the player.",
        "i_f_flurryscorevenueadjustedxgoals": "Flurry, score, and venue adjusted expected goals for the player.",
        "i_f_primaryassists": "Total primary assists by the player.",
        "i_f_secondaryassists": "Total secondary assists by the player.",
        "i_f_shotsongoal": "Total shots on goal by the player.",
        "i_f_missedshots": "Total missed shots by the player.",
        "i_f_blockedshotattempts": "Total blocked shot attempts by the player.",
        "i_f_shotattempts": "Total shot attempts by the player.",
        "i_f_points": "Total points by the player.",
        "i_f_goals": "Total goals by the player.",
        "i_f_rebounds": "Total rebounds by the player.",
        "i_f_reboundgoals": "Total rebound goals by the player.",
        "i_f_freeze": "Total freezes by the player.",
        "i_f_playstopped": "Total play stoppages by the player.",
        "i_f_playcontinuedinzone": "Total continued play in zone by the player.",
        "i_f_playcontinuedoutsidezone": "Total continued play outside zone by the player.",
        "i_f_savedshotsongoal": "Total saved shots on goal by the player.",
        "i_f_savedunblockedshotattempts": "Total saved unblocked shot attempts by the player.",
        "penalties": "Total penalties taken by the player.",
        "i_f_penalityminutes": "Total penalty minutes incurred by the player.",
        "i_f_hits": "Total hits by the player.",
        "i_f_takeaways": "Total takeaways by the player.",
        "i_f_giveaways": "Total giveaways by the player.",
        "i_f_lowdangershots": "Total low danger shots by the player.",
        "i_f_mediumdangershots": "Total medium danger shots by the player.",
        "i_f_highdangershots": "Total high danger shots by the player.",
        "i_f_lowdangerxgoals": "Expected low danger goals by the player.",
        "i_f_mediumdangerxgoals": "Expected medium danger goals by the player.",
        "i_f_highdangerxgoals": "Expected high danger goals by the player.",
        "i_f_lowdangergoals": "Total low danger goals by the player.",
        "i_f_mediumdangergoals": "Total medium danger goals by the player.",
        "i_f_highdangergoals": "Total high danger goals by the player.",
        "i_f_scoreadjustedshotsattempts": "Score adjusted shot attempts by the player.",
        "i_f_unblockedshotattempts": "Total unblocked shot attempts by the player.",
        "i_f_scoreadjustedunblockedshotattempts": "Score adjusted unblocked shot attempts by the player.",
        "i_f_dzonegiveaways": "Total defensive zone giveaways by the player.",
        "i_f_xgoalsfromxreboundsofshots": "Expected goals from expected rebounds of shots by the player.",
        "i_f_xgoalsfromactualreboundsofshots": "Expected goals from actual rebounds of shots by the player.",
        "i_f_reboundxgoals": "Expected goals from rebounds by the player.",
        "i_f_xgoals_with_earned_rebounds": "Expected goals with earned rebounds by the player.",
        "i_f_xgoals_with_earned_rebounds_scoreadjusted": "Score adjusted expected goals with earned rebounds by the player.",
        "i_f_xgoals_with_earned_rebounds_scoreflurryadjusted": "Flurry and score adjusted expected goals with earned rebounds by the player.",
        "i_f_shifts": "Total shifts by the player.",
        "i_f_ozoneshiftstarts": "Total offensive zone shift starts by the player.",
        "i_f_dzoneshiftstarts": "Total defensive zone shift starts by the player.",
        "i_f_neutralzoneshiftstarts": "Total neutral zone shift starts by the player.",
        "i_f_flyshiftstarts": "Total fly shift starts by the player.",
        "i_f_ozoneshiftends": "Total offensive zone shift ends by the player.",
        "i_f_dzoneshiftends": "Total defensive zone shift ends by the player.",
        "i_f_neutralzoneshiftends": "Total neutral zone shift ends by the player.",
        "i_f_flyshiftends": "Total fly shift ends by the player.",
        "faceoffswon": "Total faceoffs won by the player.",
        "faceoffslost": "Total faceoffs lost by the player.",
        "penalityminutes": "Total penalty minutes taken by the player.",
        "penalityminutesdrawn": "Total penalty minutes drawn by the player.",
        "penaltiesdrawn": "Total penalties drawn by the player.",
        "shotsblockedbyplayer": "Total shots blocked by the player.",
        "onice_f_xongoal": "Expected shots on goal for the player's team while the player is on the ice.",
        "onice_f_xgoals": "Expected goals for the player's team while the player is on the ice.",
        "onice_f_flurryadjustedxgoals": "Flurry adjusted expected goals for the player's team while the player is on the ice.",
        "onice_f_scorevenueadjustedxgoals": "Score and venue adjusted expected goals for the player's team while the player is on the ice.",
        "onice_f_flurryscorevenueadjustedxgoals": "Flurry, score, and venue adjusted expected goals for the player's team while the player is on the ice.",
        "onice_f_shotsongoal": "Total shots on goal for the player's team while the player is on the ice.",
        "onice_f_missedshots": "Total missed shots for the player's team while the player is on the ice.",
        "onice_f_blockedshotattempts": "Total blocked shot attempts for the player's team while the player is on the ice.",
        "onice_f_shotattempts": "Total shot attempts for the player's team while the player is on the ice.",
        "onice_f_goals": "Total goals for the player's team while the player is on the ice.",
        "onice_f_rebounds": "Total rebounds for the player's team while the player is on the ice.",
        "onice_f_reboundgoals": "Total rebound goals for the player's team while the player is on the ice.",
        "onice_f_lowdangershots": "Total low danger shots for the player's team while the player is on the ice.",
        "onice_f_mediumdangershots": "Total medium danger shots for the player's team while the player is on the ice.",
        "onice_f_highdangershots": "Total high danger shots for the player's team while the player is on the ice.",
        "onice_f_lowdangerxgoals": "Expected low danger goals for the player's team while the player is on the ice.",
        "onice_f_mediumdangerxgoals": "Expected medium danger goals for the player's team while the player is on the ice.",
        "onice_f_highdangerxgoals": "Expected high danger goals for the player's team while the player is on the ice.",
        "onice_f_lowdangergoals": "Total low danger goals for the player's team while the player is on the ice.",
        "onice_f_mediumdangergoals": "Total medium danger goals for the player's team while the player is on the ice.",
        "onice_f_highdangergoals": "Total high danger goals for the player's team while the player is on the ice.",
        "onice_f_scoreadjustedshotsattempts": "Score adjusted shot attempts for the player's team while the player is on the ice.",
        "onice_f_unblockedshotattempts": "Total unblocked shot attempts for the player's team while the player is on the ice.",
        "onice_f_scoreadjustedunblockedshotattempts": "Score adjusted unblocked shot attempts for the player's team while the player is on the ice.",
        "onice_f_xgoalsfromxreboundsofshots": "Expected goals from expected rebounds of shots for the player's team while the player is on the ice.",
        "onice_f_xgoalsfromactualreboundsofshots": "Expected goals from actual rebounds of shots for the player's team while the player is on the ice.",
        "onice_f_reboundxgoals": "Expected goals from rebounds for the player's team while the player is on the ice.",
        "onice_f_xgoals_with_earned_rebounds": "Expected goals with earned rebounds for the player's team while the player is on the ice.",
        "onice_f_xgoals_with_earned_rebounds_scoreadjusted": "Score adjusted expected goals with earned rebounds for the player's team while the player is on the ice.",
        "onice_f_xgoals_with_earned_rebounds_scoreflurryadjusted": "Flurry and score adjusted expected goals with earned rebounds for the player's team while the player is on the ice.",
        "onice_a_xongoal": "Expected shots on goal against the player's team while the player is on the ice.",
        "onice_a_xgoals": "Expected goals against the player's team while the player is on the ice.",
        "onice_a_flurryadjustedxgoals": "Flurry adjusted expected goals against the player's team while the player is on the ice.",
        "onice_a_scorevenueadjustedxgoals": "Score and venue adjusted expected goals against the player's team while the player is on the ice.",
        "onice_a_flurryscorevenueadjustedxgoals": "Flurry, score, and venue adjusted expected goals against the player's team while the player is on the ice.",
        "onice_a_shotsongoal": "Total shots on goal against the player's team while the player is on the ice.",
        "onice_a_missedshots": "Total missed shots against the player's team while the player is on the ice.",
        "onice_a_blockedshotattempts": "Total blocked shot attempts against the player's team while the player is on the ice.",
        "onice_a_shotattempts": "Total shot attempts against the player's team while the player is on the ice.",
        "onice_a_goals": "Total goals against the player's team while the player is on the ice.",
        "onice_a_rebounds": "Total rebounds against the player's team while the player is on the ice.",
        "onice_a_reboundgoals": "Total rebound goals against the player's team while the player is on the ice.",
        "onice_a_lowdangershots": "Total low danger shots against the player's team while the player is on the ice.",
        "onice_a_mediumdangershots": "Total medium danger shots against the player's team while the player is on the ice.",
        "onice_a_highdangershots": "Total high danger shots against the player's team while the player is on the ice.",
        "onice_a_lowdangerxgoals": "Expected low danger goals against the player's team while the player is on the ice.",
        "onice_a_mediumdangerxgoals": "Expected medium danger goals against the player's team while the player is on the ice.",
        "onice_a_highdangerxgoals": "Expected high danger goals against the player's team while the player is on the ice.",
        "onice_a_lowdangergoals": "Total low danger goals against the player's team while the player is on the ice.",
        "onice_a_mediumdangergoals": "Total medium danger goals against the player's team while the player is on the ice.",
        "onice_a_highdangergoals": "Total high danger goals against the player's team while the player is on the ice.",
        "onice_a_scoreadjustedshotsattempts": "Score adjusted shot attempts against the player's team while the player is on the ice.",
        "onice_a_unblockedshotattempts": "Total unblocked shot attempts against the player's team while the player is on the ice.",
        "onice_a_scoreadjustedunblockedshotattempts": "Score adjusted unblocked shot attempts against the player's team while the player is on the ice.",
        "onice_a_xgoalsfromxreboundsofshots": "Expected goals from expected rebounds of shots against the player's team while the player is on the ice.",
        "onice_a_xgoalsfromactualreboundsofshots": "Expected goals from actual rebounds of shots against the player's team while the player is on the ice.",
        "onice_a_reboundxgoals": "Expected goals from rebounds against the player's team while the player is on the ice.",
        "onice_a_xgoals_with_earned_rebounds": "Expected goals with earned rebounds against the player's team while the player is on the ice.",
        "onice_a_xgoals_with_earned_rebounds_scoreadjusted": "Score adjusted expected goals with earned rebounds against the player's team while the player is on the ice.",
        "onice_a_xgoals_with_earned_rebounds_scoreflurryadjusted": "Flurry and score adjusted expected goals with earned rebounds against the player's team while the player is on the ice.",
        "office_f_xgoals": "Expected goals for the player's team while the player is off the ice.",
        "office_a_xgoals": "Expected goals against the player's team while the player is off the ice.",
        "office_f_shotattempts": "Total shot attempts for the player's team while the player is off the ice.",
        "office_a_shotattempts": "Total shot attempts against the player's team while the player is off the ice.",
        "xgoalsforaftershifts": "Expected goals for after shifts.",
        "xgoalsagainstaftershifts": "Expected goals against after shifts.",
        "corsiforaftershifts": "Corsi for after shifts.",
        "corsiagainstaftershifts": "Corsi against after shifts.",
        "fenwickforaftershifts": "Fenwick for after shifts.",
        "fenwickagainstaftershifts": "Fenwick against after shifts."
    },
    "player_stats_playoffs": {
        "player_id": "Identifier for the player.",
        "name": "Name of the player.",
        "team": "3 Letter abbreviation of the players team",
        "season": "Season in which the data was recorded.",
        "position": "Position of the player as a letter (G, D, L, R, C).",
        "search_vector": "Search vector for text search capabilities.",
        "games_played": "Number of games played by the player.",
        "icetime": "Total ice time of the player in minutes.",
        "shifts": "Total number of shifts taken by the player.",
        "icetimerank": "Rank of ice time among all players.",
        "timeonbench": "Total time spent on the bench by the player in minutes.",
        "gamescore": "Overall game score rating for the player.",
        "onice_xgoalspercentage": "On-ice expected goals percentage.",
        "office_xgoalspercentage": "Off-ice expected goals percentage.",
        "onice_corsipercentage": "On-ice Corsi percentage, a measure of shot attempt differential.",
        "office_corsipercentage": "Off-ice Corsi percentage, a measure of shot attempt differential.",
        "onice_fenwickpercentage": "On-ice Fenwick percentage, a measure of unblocked shot attempt differential.",
        "office_fenwickpercentage": "Off-ice Fenwick percentage, a measure of unblocked shot attempt differential.",
        "i_f_xongoal": "Expected shots on goal for the player.",
        "i_f_xgoals": "Expected goals for the player.",
        "i_f_xrebounds": "Expected rebounds for the player.",
        "i_f_xfreeze": "Expected freezes for the player.",
        "i_f_xplaystopped": "Expected play stoppages for the player.",
        "i_f_xplaycontinuedinzone": "Expected continued play in zone for the player.",
        "i_f_xplaycontinuedoutsidezone": "Expected continued play outside zone for the player.",
        "i_f_flurryadjustedxgoals": "Flurry adjusted expected goals for the player.",
        "i_f_scorevenueadjustedxgoals": "Score and venue adjusted expected goals for the player.",
        "i_f_flurryscorevenueadjustedxgoals": "Flurry, score, and venue adjusted expected goals for the player.",
        "i_f_primaryassists": "Total primary assists by the player.",
        "i_f_secondaryassists": "Total secondary assists by the player.",
        "i_f_shotsongoal": "Total shots on goal by the player.",
        "i_f_missedshots": "Total missed shots by the player.",
        "i_f_blockedshotattempts": "Total blocked shot attempts by the player.",
        "i_f_shotattempts": "Total shot attempts by the player.",
        "i_f_points": "Total points by the player.",
        "i_f_goals": "Total goals by the player.",
        "i_f_rebounds": "Total rebounds by the player.",
        "i_f_reboundgoals": "Total rebound goals by the player.",
        "i_f_freeze": "Total freezes by the player.",
        "i_f_playstopped": "Total play stoppages by the player.",
        "i_f_playcontinuedinzone": "Total continued play in zone by the player.",
        "i_f_playcontinuedoutsidezone": "Total continued play outside zone by the player.",
        "i_f_savedshotsongoal": "Total saved shots on goal by the player.",
        "i_f_savedunblockedshotattempts": "Total saved unblocked shot attempts by the player.",
        "penalties": "Total penalties taken by the player.",
        "i_f_penalityminutes": "Total penalty minutes incurred by the player.",
        "i_f_hits": "Total hits by the player.",
        "i_f_takeaways": "Total takeaways by the player.",
        "i_f_giveaways": "Total giveaways by the player.",
        "i_f_lowdangershots": "Total low danger shots by the player.",
        "i_f_mediumdangershots": "Total medium danger shots by the player.",
        "i_f_highdangershots": "Total high danger shots by the player.",
        "i_f_lowdangerxgoals": "Expected low danger goals by the player.",
        "i_f_mediumdangerxgoals": "Expected medium danger goals by the player.",
        "i_f_highdangerxgoals": "Expected high danger goals by the player.",
        "i_f_lowdangergoals": "Total low danger goals by the player.",
        "i_f_mediumdangergoals": "Total medium danger goals by the player.",
        "i_f_highdangergoals": "Total high danger goals by the player.",
        "i_f_scoreadjustedshotsattempts": "Score adjusted shot attempts by the player.",
        "i_f_unblockedshotattempts": "Total unblocked shot attempts by the player.",
        "i_f_scoreadjustedunblockedshotattempts": "Score adjusted unblocked shot attempts by the player.",
        "i_f_dzonegiveaways": "Total defensive zone giveaways by the player.",
        "i_f_xgoalsfromxreboundsofshots": "Expected goals from expected rebounds of shots by the player.",
        "i_f_xgoalsfromactualreboundsofshots": "Expected goals from actual rebounds of shots by the player.",
        "i_f_reboundxgoals": "Expected goals from rebounds by the player.",
        "i_f_xgoals_with_earned_rebounds": "Expected goals with earned rebounds by the player.",
        "i_f_xgoals_with_earned_rebounds_scoreadjusted": "Score adjusted expected goals with earned rebounds by the player.",
        "i_f_xgoals_with_earned_rebounds_scoreflurryadjusted": "Flurry and score adjusted expected goals with earned rebounds by the player.",
        "i_f_shifts": "Total shifts by the player.",
        "i_f_ozoneshiftstarts": "Total offensive zone shift starts by the player.",
        "i_f_dzoneshiftstarts": "Total defensive zone shift starts by the player.",
        "i_f_neutralzoneshiftstarts": "Total neutral zone shift starts by the player.",
        "i_f_flyshiftstarts": "Total fly shift starts by the player.",
        "i_f_ozoneshiftends": "Total offensive zone shift ends by the player.",
        "i_f_dzoneshiftends": "Total defensive zone shift ends by the player.",
        "i_f_neutralzoneshiftends": "Total neutral zone shift ends by the player.",
        "i_f_flyshiftends": "Total fly shift ends by the player.",
        "faceoffswon": "Total faceoffs won by the player.",
        "faceoffslost": "Total faceoffs lost by the player.",
        "penalityminutes": "Total penalty minutes taken by the player.",
        "penalityminutesdrawn": "Total penalty minutes drawn by the player.",
        "penaltiesdrawn": "Total penalties drawn by the player.",
        "shotsblockedbyplayer": "Total shots blocked by the player.",
        "onice_f_xongoal": "Expected shots on goal for the player's team while the player is on the ice.",
        "onice_f_xgoals": "Expected goals for the player's team while the player is on the ice.",
        "onice_f_flurryadjustedxgoals": "Flurry adjusted expected goals for the player's team while the player is on the ice.",
        "onice_f_scorevenueadjustedxgoals": "Score and venue adjusted expected goals for the player's team while the player is on the ice.",
        "onice_f_flurryscorevenueadjustedxgoals": "Flurry, score, and venue adjusted expected goals for the player's team while the player is on the ice.",
        "onice_f_shotsongoal": "Total shots on goal for the player's team while the player is on the ice.",
        "onice_f_missedshots": "Total missed shots for the player's team while the player is on the ice.",
        "onice_f_blockedshotattempts": "Total blocked shot attempts for the player's team while the player is on the ice.",
        "onice_f_shotattempts": "Total shot attempts for the player's team while the player is on the ice.",
        "onice_f_goals": "Total goals for the player's team while the player is on the ice.",
        "onice_f_rebounds": "Total rebounds for the player's team while the player is on the ice.",
        "onice_f_reboundgoals": "Total rebound goals for the player's team while the player is on the ice.",
        "onice_f_lowdangershots": "Total low danger shots for the player's team while the player is on the ice.",
        "onice_f_mediumdangershots": "Total medium danger shots for the player's team while the player is on the ice.",
        "onice_f_highdangershots": "Total high danger shots for the player's team while the player is on the ice.",
        "onice_f_lowdangerxgoals": "Expected low danger goals for the player's team while the player is on the ice.",
        "onice_f_mediumdangerxgoals": "Expected medium danger goals for the player's team while the player is on the ice.",
        "onice_f_highdangerxgoals": "Expected high danger goals for the player's team while the player is on the ice.",
        "onice_f_lowdangergoals": "Total low danger goals for the player's team while the player is on the ice.",
        "onice_f_mediumdangergoals": "Total medium danger goals for the player's team while the player is on the ice.",
        "onice_f_highdangergoals": "Total high danger goals for the player's team while the player is on the ice.",
        "onice_f_scoreadjustedshotsattempts": "Score adjusted shot attempts for the player's team while the player is on the ice.",
        "onice_f_unblockedshotattempts": "Total unblocked shot attempts for the player's team while the player is on the ice.",
        "onice_f_scoreadjustedunblockedshotattempts": "Score adjusted unblocked shot attempts for the player's team while the player is on the ice.",
        "onice_f_xgoalsfromxreboundsofshots": "Expected goals from expected rebounds of shots for the player's team while the player is on the ice.",
        "onice_f_xgoalsfromactualreboundsofshots": "Expected goals from actual rebounds of shots for the player's team while the player is on the ice.",
        "onice_f_reboundxgoals": "Expected goals from rebounds for the player's team while the player is on the ice.",
        "onice_f_xgoals_with_earned_rebounds": "Expected goals with earned rebounds for the player's team while the player is on the ice.",
        "onice_f_xgoals_with_earned_rebounds_scoreadjusted": "Score adjusted expected goals with earned rebounds for the player's team while the player is on the ice.",
        "onice_f_xgoals_with_earned_rebounds_scoreflurryadjusted": "Flurry and score adjusted expected goals with earned rebounds for the player's team while the player is on the ice.",
        "onice_a_xongoal": "Expected shots on goal against the player's team while the player is on the ice.",
        "onice_a_xgoals": "Expected goals against the player's team while the player is on the ice.",
        "onice_a_flurryadjustedxgoals": "Flurry adjusted expected goals against the player's team while the player is on the ice.",
        "onice_a_scorevenueadjustedxgoals": "Score and venue adjusted expected goals against the player's team while the player is on the ice.",
        "onice_a_flurryscorevenueadjustedxgoals": "Flurry, score, and venue adjusted expected goals against the player's team while the player is on the ice.",
        "onice_a_shotsongoal": "Total shots on goal against the player's team while the player is on the ice.",
        "onice_a_missedshots": "Total missed shots against the player's team while the player is on the ice.",
        "onice_a_blockedshotattempts": "Total blocked shot attempts against the player's team while the player is on the ice.",
        "onice_a_shotattempts": "Total shot attempts against the player's team while the player is on the ice.",
        "onice_a_goals": "Total goals against the player's team while the player is on the ice.",
        "onice_a_rebounds": "Total rebounds against the player's team while the player is on the ice.",
        "onice_a_reboundgoals": "Total rebound goals against the player's team while the player is on the ice.",
        "onice_a_lowdangershots": "Total low danger shots against the player's team while the player is on the ice.",
        "onice_a_mediumdangershots": "Total medium danger shots against the player's team while the player is on the ice.",
        "onice_a_highdangershots": "Total high danger shots against the player's team while the player is on the ice.",
        "onice_a_lowdangerxgoals": "Expected low danger goals against the player's team while the player is on the ice.",
        "onice_a_mediumdangerxgoals": "Expected medium danger goals against the player's team while the player is on the ice.",
        "onice_a_highdangerxgoals": "Expected high danger goals against the player's team while the player is on the ice.",
        "onice_a_lowdangergoals": "Total low danger goals against the player's team while the player is on the ice.",
        "onice_a_mediumdangergoals": "Total medium danger goals against the player's team while the player is on the ice.",
        "onice_a_highdangergoals": "Total high danger goals against the player's team while the player is on the ice.",
        "onice_a_scoreadjustedshotsattempts": "Score adjusted shot attempts against the player's team while the player is on the ice.",
        "onice_a_unblockedshotattempts": "Total unblocked shot attempts against the player's team while the player is on the ice.",
        "onice_a_scoreadjustedunblockedshotattempts": "Score adjusted unblocked shot attempts against the player's team while the player is on the ice.",
        "onice_a_xgoalsfromxreboundsofshots": "Expected goals from expected rebounds of shots against the player's team while the player is on the ice.",
        "onice_a_xgoalsfromactualreboundsofshots": "Expected goals from actual rebounds of shots against the player's team while the player is on the ice.",
        "onice_a_reboundxgoals": "Expected goals from rebounds against the player's team while the player is on the ice.",
        "onice_a_xgoals_with_earned_rebounds": "Expected goals with earned rebounds against the player's team while the player is on the ice.",
        "onice_a_xgoals_with_earned_rebounds_scoreadjusted": "Score adjusted expected goals with earned rebounds against the player's team while the player is on the ice.",
        "onice_a_xgoals_with_earned_rebounds_scoreflurryadjusted": "Flurry and score adjusted expected goals with earned rebounds against the player's team while the player is on the ice.",
        "office_f_xgoals": "Expected goals for the player's team while the player is off the ice.",
        "office_a_xgoals": "Expected goals against the player's team while the player is off the ice.",
        "office_f_shotattempts": "Total shot attempts for the player's team while the player is off the ice.",
        "office_a_shotattempts": "Total shot attempts against the player's team while the player is off the ice.",
        "xgoalsforaftershifts": "Expected goals for after shifts.",
        "xgoalsagainstaftershifts": "Expected goals against after shifts.",
        "corsiforaftershifts": "Corsi for after shifts.",
        "corsiagainstaftershifts": "Corsi against after shifts.",
        "fenwickforaftershifts": "Fenwick for after shifts.",
        "fenwickagainstaftershifts": "Fenwick against after shifts."
    },
    "team_stats": {
        "season": "Season in which the data was recorded.",
        "team": "3 Letter abbreviation of the team",
        "season": "Season in which the data was recorded.",
        "games_played": "Number of games played by the team.",
        "iceTime": "Total ice time for the team in minutes.",
        "xGoalsPercentage": "Expected goals percentage.",
        "corsiPercentage": "Corsi percentage, a measure of shot attempt differential.",
        "fenwickPercentage": "Fenwick percentage, a measure of unblocked shot attempt differential.",
        "xOnGoalFor": "Expected shots on goal for.",
        "xGoalsFor": "Expected goals for.",
        "xReboundsFor": "Expected rebounds for.",
        "xFreezeFor": "Expected freezes for.",
        "xPlayStoppedFor": "Expected play stoppages for.",
        "xPlayContinuedInZoneFor": "Expected continued play in zone for.",
        "xPlayContinuedOutsideZoneFor": "Expected continued play outside zone for.",
        "flurryAdjustedxGoalsFor": "Flurry adjusted expected goals for.",
        "scoreVenueAdjustedxGoalsFor": "Score and venue adjusted expected goals for.",
        "flurryScoreVenueAdjustedxGoalsFor": "Flurry, score, and venue adjusted expected goals for.",
        "lowDangerxGoalsFor": "Expected low danger goals for.",
        "mediumDangerxGoalsFor": "Expected medium danger goals for.",
        "highDangerxGoalsFor": "Expected high danger goals for.",
        "xGoalsFromxReboundsOfShotsFor": "Expected goals from expected rebounds of shots for.",
        "xGoalsFromActualReboundsOfShotsFor": "Expected goals from actual rebounds of shots for.",
        "reboundxGoalsFor": "Expected goals from rebounds for.",
        "totalShotCreditFor": "Total shot credit for.",
        "scoreAdjustedTotalShotCreditFor": "Score adjusted total shot credit for.",
        "scoreFlurryAdjustedTotalShotCreditFor": "Score and flurry adjusted total shot credit for.",
        "xOnGoalAgainst": "Expected shots on goal against.",
        "xGoalsAgainst": "Expected goals against.",
        "xReboundsAgainst": "Expected rebounds against.",
        "xFreezeAgainst": "Expected freezes against.",
        "xPlayStoppedAgainst": "Expected play stoppages against.",
        "xPlayContinuedInZoneAgainst": "Expected continued play in zone against.",
        "xPlayContinuedOutsideZoneAgainst": "Expected continued play outside zone against.",
        "flurryAdjustedxGoalsAgainst": "Flurry adjusted expected goals against.",
        "scoreVenueAdjustedxGoalsAgainst": "Score and venue adjusted expected goals against.",
        "flurryScoreVenueAdjustedxGoalsAgainst": "Flurry, score, and venue adjusted expected goals against.",
        "lowDangerxGoalsAgainst": "Expected low danger goals against.",
        "mediumDangerxGoalsAgainst": "Expected medium danger goals against.",
        "highDangerxGoalsAgainst": "Expected high danger goals against.",
        "xGoalsFromxReboundsOfShotsAgainst": "Expected goals from expected rebounds of shots against.",
        "xGoalsFromActualReboundsOfShotsAgainst": "Expected goals from actual rebounds of shots against.",
        "reboundxGoalsAgainst": "Expected goals from rebounds against.",
        "totalShotCreditAgainst": "Total shot credit against.",
        "scoreAdjustedTotalShotCreditAgainst": "Score adjusted total shot credit against.",
        "scoreFlurryAdjustedTotalShotCreditAgainst": "Score and flurry adjusted total shot credit against.",
        "shotsOnGoalFor": "Total shots on goal for the team.",
        "missedShotsFor": "Total missed shots for the team.",
        "blockedShotAttemptsFor": "Total blocked shot attempts for the team.",
        "shotAttemptsFor": "Total shot attempts for the team.",
        "goalsFor": "Total goals scored by the team.",
        "reboundsFor": "Total rebounds for the team.",
        "reboundGoalsFor": "Total rebound goals for the team.",
        "freezeFor": "Total freezes for the team.",
        "playStoppedFor": "Total play stoppages for the team.",
        "playContinuedInZoneFor": "Total continued play in zone for the team.",
        "playContinuedOutsideZoneFor": "Total continued play outside zone for the team.",
        "savedShotsOnGoalFor": "Total saved shots on goal for the team.",
        "savedUnblockedShotAttemptsFor": "Total saved unblocked shot attempts for the team.",
        "penaltiesFor": "Total penalties for the team.",
        "penalityMinutesFor": "Total penalty minutes for the team.",
        "faceOffsWonFor": "Total faceoffs won by the team.",
        "hitsFor": "Total hits by the team.",
        "takeawaysFor": "Total takeaways by the team.",
        "giveawaysFor": "Total giveaways by the team.",
        "lowDangerShotsFor": "Total low danger shots for the team.",
        "mediumDangerShotsFor": "Total medium danger shots for the team.",
        "highDangerShotsFor": "Total high danger shots for the team.",
        "lowDangerGoalsFor": "Total low danger goals for the team.",
        "mediumDangerGoalsFor": "Total medium danger goals for the team.",
        "highDangerGoalsFor": "Total high danger goals for the team.",
        "scoreAdjustedShotsAttemptsFor": "Score adjusted shot attempts for the team.",
        "unblockedShotAttemptsFor": "Total unblocked shot attempts for the team.",
        "scoreAdjustedUnblockedShotAttemptsFor": "Score adjusted unblocked shot attempts for the team.",
        "dZoneGiveawaysFor": "Total defensive zone giveaways for the team.",
        "shotsOnGoalAgainst": "Total shots on goal against the team.",
        "missedShotsAgainst": "Total missed shots against the team.",
        "blockedShotAttemptsAgainst": "Total blocked shot attempts against the team.",
        "shotAttemptsAgainst": "Total shot attempts against the team.",
        "goalsAgainst": "Total goals scored against the team.",
        "reboundsAgainst": "Total rebounds against the team.",
        "reboundGoalsAgainst": "Total rebound goals against the team.",
        "freezeAgainst": "Total freezes against the team.",
        "playStoppedAgainst": "Total play stoppages against the team.",
        "playContinuedInZoneAgainst": "Total continued play in zone against the team.",
        "playContinuedOutsideZoneAgainst": "Total continued play outside zone against the team.",
        "savedShotsOnGoalAgainst": "Total saved shots on goal against the team.",
        "savedUnblockedShotAttemptsAgainst": "Total saved unblocked shot attempts against the team.",
        "penaltiesAgainst": "Total penalties against the team.",
        "penalityMinutesAgainst": "Total penalty minutes against the team.",
        "faceOffsWonAgainst": "Total faceoffs won against the team.",
        "hitsAgainst": "Total hits against the team.",
        "takeawaysAgainst": "Total takeaways against the team.",
        "giveawaysAgainst": "Total giveaways against the team.",
        "lowDangerShotsAgainst": "Total low danger shots against the team.",
        "mediumDangerShotsAgainst": "Total medium danger shots against the team.",
        "highDangerShotsAgainst": "Total high danger shots against the team.",
        "lowDangerGoalsAgainst": "Total low danger goals against the team.",
        "mediumDangerGoalsAgainst": "Total medium danger goals against the team.",
        "highDangerGoalsAgainst": "Total high danger goals against the team.",
        "scoreAdjustedShotsAttemptsAgainst": "Score adjusted shot attempts against the team.",
        "unblockedShotAttemptsAgainst": "Total unblocked shot attempts against the team.",
        "scoreAdjustedUnblockedShotAttemptsAgainst": "Score adjusted unblocked shot attempts against the team.",
        "dZoneGiveawaysAgainst": "Total defensive zone giveaways against the team."
    },
    "team_stats_playoffs": {
        "season": "Season in which the data was recorded.",
        "team": "3 Letter abbreviation of the players team",
        "situation": "Game situation or context for the statistics.",
        "games_played": "Number of games played by the team.",
        "iceTime": "Total ice time for the team in minutes.",
        "xGoalsPercentage": "Expected goals percentage.",
        "corsiPercentage": "Corsi percentage, a measure of shot attempt differential.",
        "fenwickPercentage": "Fenwick percentage, a measure of unblocked shot attempt differential.",
        "xOnGoalFor": "Expected shots on goal for.",
        "xGoalsFor": "Expected goals for.",
        "xReboundsFor": "Expected rebounds for.",
        "xFreezeFor": "Expected freezes for.",
        "xPlayStoppedFor": "Expected play stoppages for.",
        "xPlayContinuedInZoneFor": "Expected continued play in zone for.",
        "xPlayContinuedOutsideZoneFor": "Expected continued play outside zone for.",
        "flurryAdjustedxGoalsFor": "Flurry adjusted expected goals for.",
        "scoreVenueAdjustedxGoalsFor": "Score and venue adjusted expected goals for.",
        "flurryScoreVenueAdjustedxGoalsFor": "Flurry, score, and venue adjusted expected goals for.",
        "lowDangerxGoalsFor": "Expected low danger goals for.",
        "mediumDangerxGoalsFor": "Expected medium danger goals for.",
        "highDangerxGoalsFor": "Expected high danger goals for.",
        "xGoalsFromxReboundsOfShotsFor": "Expected goals from expected rebounds of shots for.",
        "xGoalsFromActualReboundsOfShotsFor": "Expected goals from actual rebounds of shots for.",
        "reboundxGoalsFor": "Expected goals from rebounds for.",
        "totalShotCreditFor": "Total shot credit for.",
        "scoreAdjustedTotalShotCreditFor": "Score adjusted total shot credit for.",
        "scoreFlurryAdjustedTotalShotCreditFor": "Score and flurry adjusted total shot credit for.",
        "xOnGoalAgainst": "Expected shots on goal against.",
        "xGoalsAgainst": "Expected goals against.",
        "xReboundsAgainst": "Expected rebounds against.",
        "xFreezeAgainst": "Expected freezes against.",
        "xPlayStoppedAgainst": "Expected play stoppages against.",
        "xPlayContinuedInZoneAgainst": "Expected continued play in zone against.",
        "xPlayContinuedOutsideZoneAgainst": "Expected continued play outside zone against.",
        "flurryAdjustedxGoalsAgainst": "Flurry adjusted expected goals against.",
        "scoreVenueAdjustedxGoalsAgainst": "Score and venue adjusted expected goals against.",
        "flurryScoreVenueAdjustedxGoalsAgainst": "Flurry, score, and venue adjusted expected goals against.",
        "lowDangerxGoalsAgainst": "Expected low danger goals against.",
        "mediumDangerxGoalsAgainst": "Expected medium danger goals against.",
        "highDangerxGoalsAgainst": "Expected high danger goals against.",
        "xGoalsFromxReboundsOfShotsAgainst": "Expected goals from expected rebounds of shots against.",
        "xGoalsFromActualReboundsOfShotsAgainst": "Expected goals from actual rebounds of shots against.",
        "reboundxGoalsAgainst": "Expected goals from rebounds against.",
        "totalShotCreditAgainst": "Total shot credit against.",
        "scoreAdjustedTotalShotCreditAgainst": "Score adjusted total shot credit against.",
        "scoreFlurryAdjustedTotalShotCreditAgainst": "Score and flurry adjusted total shot credit against.",
        "shotsOnGoalFor": "Total shots on goal for the team.",
        "missedShotsFor": "Total missed shots for the team.",
        "blockedShotAttemptsFor": "Total blocked shot attempts for the team.",
        "shotAttemptsFor": "Total shot attempts for the team.",
        "goalsFor": "Total goals scored by the team.",
        "reboundsFor": "Total rebounds for the team.",
        "reboundGoalsFor": "Total rebound goals for the team.",
        "freezeFor": "Total freezes for the team.",
        "playStoppedFor": "Total play stoppages for the team.",
        "playContinuedInZoneFor": "Total continued play in zone for the team.",
        "playContinuedOutsideZoneFor": "Total continued play outside zone for the team.",
        "savedShotsOnGoalFor": "Total saved shots on goal for the team.",
        "savedUnblockedShotAttemptsFor": "Total saved unblocked shot attempts for the team.",
        "penaltiesFor": "Total penalties for the team.",
        "penalityMinutesFor": "Total penalty minutes for the team.",
        "faceOffsWonFor": "Total faceoffs won by the team.",
        "hitsFor": "Total hits by the team.",
        "takeawaysFor": "Total takeaways by the team.",
        "giveawaysFor": "Total giveaways by the team.",
        "lowDangerShotsFor": "Total low danger shots for the team.",
        "mediumDangerShotsFor": "Total medium danger shots for the team.",
        "highDangerShotsFor": "Total high danger shots for the team.",
        "lowDangerGoalsFor": "Total low danger goals for the team.",
        "mediumDangerGoalsFor": "Total medium danger goals for the team.",
        "highDangerGoalsFor": "Total high danger goals for the team.",
        "scoreAdjustedShotsAttemptsFor": "Score adjusted shot attempts for the team.",
        "unblockedShotAttemptsFor": "Total unblocked shot attempts for the team.",
        "scoreAdjustedUnblockedShotAttemptsFor": "Score adjusted unblocked shot attempts for the team.",
        "dZoneGiveawaysFor": "Total defensive zone giveaways for the team.",
        "shotsOnGoalAgainst": "Total shots on goal against the team.",
        "missedShotsAgainst": "Total missed shots against the team.",
        "blockedShotAttemptsAgainst": "Total blocked shot attempts against the team.",
        "shotAttemptsAgainst": "Total shot attempts against the team.",
        "goalsAgainst": "Total goals scored against the team.",
        "reboundsAgainst": "Total rebounds against the team.",
        "reboundGoalsAgainst": "Total rebound goals against the team.",
        "freezeAgainst": "Total freezes against the team.",
        "playStoppedAgainst": "Total play stoppages against the team.",
        "playContinuedInZoneAgainst": "Total continued play in zone against the team.",
        "playContinuedOutsideZoneAgainst": "Total continued play outside zone against the team.",
        "savedShotsOnGoalAgainst": "Total saved shots on goal against the team.",
        "savedUnblockedShotAttemptsAgainst": "Total saved unblocked shot attempts against the team.",
        "penaltiesAgainst": "Total penalties against the team.",
        "penalityMinutesAgainst": "Total penalty minutes against the team.",
        "faceOffsWonAgainst": "Total faceoffs won against the team.",
        "hitsAgainst": "Total hits against the team.",
        "takeawaysAgainst": "Total takeaways against the team.",
        "giveawaysAgainst": "Total giveaways against the team.",
        "lowDangerShotsAgainst": "Total low danger shots against the team.",
        "mediumDangerShotsAgainst": "Total medium danger shots against the team.",
        "highDangerShotsAgainst": "Total high danger shots against the team.",
        "lowDangerGoalsAgainst": "Total low danger goals against the team.",
        "mediumDangerGoalsAgainst": "Total medium danger goals against the team.",
        "highDangerGoalsAgainst": "Total high danger goals against the team.",
        "scoreAdjustedShotsAttemptsAgainst": "Score adjusted shot attempts against the team.",
        "unblockedShotAttemptsAgainst": "Total unblocked shot attempts against the team.",
        "scoreAdjustedUnblockedShotAttemptsAgainst": "Score adjusted unblocked shot attempts against the team.",
        "dZoneGiveawaysAgainst": "Total defensive zone giveaways against the team."
    },
    "team_games": {
        "team": "Name of the team.",
        "season": "Season in which the game was played.",
        "name": "Name of the player or team.",
        "gameid": "Unique identifier for the game.",
        "playerteam": "The team of the player.",
        "opposingteam": "The team opposing the playerteam.",
        "home_or_away": "Indicates whether the game was played at home or away.",
        "gamedate": "Date when the game was played.",
        "position": "Position or ranking within the team or league.",
        "situation": "Game situation or context for the statistics.",
        "playoffgame": "Indicates whether the game is a playoff game.",
        "xgoalspercentage": "Expected goals percentage.",
        "corsipercentage": "Corsi percentage, a measure of shot attempt differential.",
        "fenwickpercentage": "Fenwick percentage, a measure of unblocked shot attempt differential.",
        "icetime": "Total ice time for the team in minutes.",
        "xongoalfor": "Expected shots on goal for the team.",
        "xgoalsfor": "Expected goals for the team.",
        "xreboundsfor": "Expected rebounds for the team.",
        "xfreezefor": "Expected freezes for the team.",
        "xplaystoppedfor": "Expected play stoppages for the team.",
        "xplaycontinuedinzonefor": "Expected continued play in zone for the team.",
        "xplaycontinuedoutsidezonefor": "Expected continued play outside zone for the team.",
        "flurryadjustedxgoalsfor": "Flurry adjusted expected goals for the team.",
        "scorevenueadjustedxgoalsfor": "Score and venue adjusted expected goals for the team.",
        "flurryscorevenueadjustedxgoalsfor": "Flurry, score, and venue adjusted expected goals for the team.",
        "lowdangerxgoalsfor": "Expected low danger goals for the team.",
        "mediumdangerxgoalsfor": "Expected medium danger goals for the team.",
        "highdangerxgoalsfor": "Expected high danger goals for the team.",
        "xgoalsfromxreboundsofshotsfor": "Expected goals from expected rebounds of shots for the team.",
        "xgoalsfromactualreboundsofshotsfor": "Expected goals from actual rebounds of shots for the team.",
        "reboundxgoalsfor": "Expected goals from rebounds for the team.",
        "totalshotcreditfor": "Total shot credit for the team.",
        "scoreadjustedtotalshotcreditfor": "Score adjusted total shot credit for the team.",
        "scoreflurryadjustedtotalshotcreditfor": "Score and flurry adjusted total shot credit for the team.",
        "xongoalagainst": "Expected shots on goal against the team.",
        "xgoalsagainst": "Expected goals against the team.",
        "xreboundsagainst": "Expected rebounds against the team.",
        "xfreezeagainst": "Expected freezes against the team.",
        "xplaystoppedagainst": "Expected play stoppages against the team.",
        "xplaycontinuedinzoneagainst": "Expected continued play in zone against the team.",
        "xplaycontinuedoutsidezoneagainst": "Expected continued play outside zone against the team.",
        "flurryadjustedxgoalsagainst": "Flurry adjusted expected goals against the team.",
        "scorevenueadjustedxgoalsagainst": "Score and venue adjusted expected goals against the team.",
        "flurryscorevenueadjustedxgoalsagainst": "Flurry, score, and venue adjusted expected goals against the team.",
        "lowdangerxgoalsagainst": "Expected low danger goals against the team.",
        "mediumdangerxgoalsagainst": "Expected medium danger goals against the team.",
        "highdangerxgoalsagainst": "Expected high danger goals against the team.",
        "xgoalsfromxreboundsofshotsagainst": "Expected goals from expected rebounds of shots against the team.",
        "xgoalsfromactualreboundsofshotsagainst": "Expected goals from actual rebounds of shots against the team.",
        "reboundxgoalsagainst": "Expected goals from rebounds against the team.",
        "totalshotcreditagainst": "Total shot credit against the team.",
        "scoreadjustedtotalshotcreditagainst": "Score adjusted total shot credit against the team.",
        "scoreflurryadjustedtotalshotcreditagainst": "Score and flurry adjusted total shot credit against the team.",
        "shotsongoalfor": "Total shots on goal for the team.",
        "missedshotsfor": "Total missed shots for the team.",
        "blockedshotattemptsfor": "Total blocked shot attempts for the team.",
        "shotattemptsfor": "Total shot attempts for the team.",
        "goalsfor": "Total goals scored by the team.",
        "reboundsfor": "Total rebounds for the team.",
        "reboundgoalsfor": "Total rebound goals for the team.",
        "freezefor": "Total freezes for the team.",
        "playstoppedfor": "Total play stoppages for the team.",
        "playcontinuedinzonefor": "Total continued play in zone for the team.",
        "playcontinuedoutsidezonefor": "Total continued play outside zone for the team.",
        "savedshotsongoalfor": "Total saved shots on goal for the team.",
        "savedunblockedshotattemptsfor": "Total saved unblocked shot attempts for the team.",
        "penaltiesfor": "Total penalties for the team.",
        "penalityminutesfor": "Total penalty minutes for the team.",
        "faceoffswonfor": "Total faceoffs won by the team.",
        "hitsfor": "Total hits by the team.",
        "takeawaysfor": "Total takeaways by the team.",
        "giveawaysfor": "Total giveaways by the team.",
        "lowdangershotsfor": "Total low danger shots for the team.",
        "mediumdangershotsfor": "Total medium danger shots for the team.",
        "highdangershotsfor": "Total high danger shots for the team.",
        "lowdangergoalsfor": "Total low danger goals for the team.",
        "mediumdangergoalsfor": "Total medium danger goals for the team.",
        "highdangergoalsfor": "Total high danger goals for the team.",
        "scoreadjustedshotsattemptsfor": "Score adjusted shot attempts for the team.",
        "unblockedshotattemptsfor": "Total unblocked shot attempts for the team.",
        "scoreadjustedunblockedshotattemptsfor": "Score adjusted unblocked shot attempts for the team.",
        "dzonegiveawaysfor": "Total defensive zone giveaways for the team.",
        "shotsongoalagainst": "Total shots on goal against the team.",
        "missedshotsagainst": "Total missed shots against the team.",
        "blockedshotattemptsagainst": "Total blocked shot attempts against the team.",
        "shotattemptsagainst": "Total shot attempts against the team.",
        "goalsagainst": "Total goals scored against the team.",
        "reboundsagainst": "Total rebounds against the team.",
        "reboundgoalsagainst": "Total rebound goals against the team.",
        "freezeagainst": "Total freezes against the team.",
        "playstoppedagainst": "Total play stoppages against the team.",
        "playcontinuedinzoneagainst": "Total continued play in zone against the team.",
        "playcontinuedoutsidezoneagainst": "Total continued play outside zone against the team.",
        "savedshotsongoalagainst": "Total saved shots on goal against the team.",
        "savedunblockedshotattemptsagainst": "Total saved unblocked shot attempts against the team.",
        "penaltiesagainst": "Total penalties against the team.",
        "penalityminutesagainst": "Total penalty minutes against the team.",
        "faceoffswonagainst": "Total faceoffs won against the team.",
        "hitsagainst": "Total hits against the team.",
        "takeawaysagainst": "Total takeaways against the team.",
        "giveawaysagainst": "Total giveaways against the team.",
        "lowdangershotsagainst": "Total low danger shots against the team.",
        "mediumdangershotsagainst": "Total medium danger shots against the team.",
        "highdangershotsagainst": "Total high danger shots against the team.",
        "lowdangergoalsagainst": "Total low danger goals against the team.",
        "mediumdangergoalsagainst": "Total medium danger goals against the team.",
        "highdangergoalsagainst": "Total high danger goals against the team.",
        "scoreadjustedshotsattemptsagainst": "Score adjusted shot attempts against the team.",
        "unblockedshotattemptsagainst": "Total unblocked shot attempts against the team.",
        "scoreadjustedunblockedshotattemptsagainst": "Score adjusted unblocked shot attempts against the team.",
        "dzonegiveawaysagainst": "Total defensive zone giveaways against the team."
    }
}